spring:
  profiles:
    active: develop
  application:
    name: bot
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bot
      username: mongo
      password: mongo
      authentication-database: admin

server:
  port: 8080

app:
  telegram:
    token: ${TOKEN}
    bot-name: book_tracker_bot
    creator-id: ${AUTHOR}
  book-api:
    api-key: ${API_KEY}
    base-url: https://www.googleapis.com/books/v1
  scheduler:
    update-info-delay: 5d
    check-release-delay: 1d

logging:
  config: classpath:log4j2-plain.xml

---

spring:
  config:
    activate:
      on-profile: develop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: debug
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver






