spring:
  profiles:
    active: test
  application:
    name: bot

server:
  port: 8080

app:
  telegram-token: ${TOKEN}
  telegram-bot-name: book_tracker_bot
  api-key: ${api-key}
  book-api-base-url: https://www.googleapis.com/books/v1

---


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host}:5432/${db-name}
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



