spring:
  profiles:
    active: test
  application:
    name: bot

server:
  port: 8080

app:
  telegram-token: ${TOKEN}
  telegram-bot-name: book_tracker_bot
  api-key: ${api-key}
  book-api-base-url: https://www.googleapis.com/books/v1

---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: username
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

