spring:
  profiles:
    active: test
  application:
    name: bot

server:
  port: 8080

app:
  telegram-token: ${TOKEN}
  telegram-bot-name: book_tracker_bot
  api-key: ${api-key}
  book-api-base-url: https://www.googleapis.com/books/v1

---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true

