spring:
  profiles:
    active: debug    # поменять чтобы сменить профиль
  application:
    name: bot

server:
  port: 8080

app:
  telegram-token: ${TOKEN}
  telegram-bot-name: book_tracker_bot
  api-key: ${API_KEY}
  book-api-base-url: https://www.googleapis.com/books/v1

---

spring:
  config:
    activate:
      on-profile: develop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

---

logging:
  level:
    org.hibernate: error
    org.springframework.web: debug

server:
  error:
    include-stacktrace: never

spring:
  output:
    ansi:
      enabled: ALWAYS
  config:
    activate:
      on-profile: debug
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver






